export const Devices: string[] = [
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPad Pro 11-inch (4th generation)",
    "iPad Pro 12.9-inch (6th generation)",
    "iPad Air (5th generation)",
    "iPad Mini (6th generation)",
    "MacBook Air (M1)",
    "MacBook Air (M2)",
    "MacBook Pro 13-inch (M1)",
    "MacBook Pro 14-inch (M1 Pro/Max)",
    "MacBook Pro 16-inch (M1 Pro/Max)",
    "iMac 24-inch (M1)",
    "iMac 27-inch (Intel)",
    "Apple Watch Series 8",
    "Apple Watch Ultra",
    "Apple Watch SE (2nd generation)",
    "Samsung Galaxy S23",
    "Samsung Galaxy S23 Ultra",
    "Samsung Galaxy Tab S9",
    "Samsung Galaxy Tab S9 Ultra",
    "Google Pixel 7",
    "Google Pixel 7 Pro",
    "Microsoft Surface Pro 9",
    "Microsoft Surface Laptop 5",
    "Dell XPS 13 (2023)",
    "HP Spectre x360 (2023)",
    "Lenovo ThinkPad X1 Carbon (2023)",
    "PlayStation 5",
    "Xbox Series X",
    "Xbox Series S",
    "Nintendo Switch OLED",
    "Sony Bravia XR A95K",
    "LG C3 OLED TV",
    "Google Pixelbook Go",
    "Acer Chromebook Spin 713",
    "ASUS Chromebook Flip CX5",
    "Samsung Galaxy Chromebook 2",
    "Lenovo Chromebook Flex 5i",
    "HP Chromebook x360 14c",
    "Dell Chromebook 3100"
];